### ISSUE TITLE
Solrizer pinned to 3.1.x

### ISSUE THREAD

**Issue by drh-stanford** [awead/solr_ead#9]
The Solrizer gem is pinned to a 2013 version, we should be able to relax it to `~> 3.1`

**Comment by anarchivist** [comment]
I think #6 addressed this (perhaps more than you'd like?). We still would need to cut a release.

**Comment by drh-stanford** [comment]
yes, fixed in 1388c03c80d1699e27d163c68d4fa4f12782ea9e
